### ISSUE TITLE
Add Simple Javascript games

### ISSUE THREAD

**Issue by anishaswain** [Anisha1234/game#1]
- The game should run over localhost
- There is no need to host the game

**Comment by ftonato** [comment]
I'll look into it!

**Comment by anishaswain** [comment]
@ftonato thanks for your interest. Please go for it.

**Comment by dushivani** [comment]
I would like to share my memory game made using HTML, JavaScript and CSS.

**Comment by Utkarsh1308** [comment]
Hey I just added a fun reaction testing game in JavaScript. Please check it out.
